import type { Metadata } from "next";
import "@/globals.css";

import { sfProDisplayFont } from "@/fonts";

export const metadata: Metadata = {
  title: "Abisola's website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
    lang="en"
    className={`${sfProDisplayFont.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
