import type { Metadata } from "next";
import "@/globals.css";

import { sfProDisplayFont } from "@/fonts";

export const metadata: Metadata = {
  title: "Arby",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
    lang="en"
    className={`${sfProDisplayFont.variable}`}
    >
      <body className="bg-[hsl(204,8%,12%)] font-sans text-white">{children}</body>
    </html>
  );
}
